### ISSUE TITLE
Validação funcionando em parte do registro 

### ISSUE THREAD

**Issue by mozgbrasil** [fnando/cpf_cnpj.js#7]
Boa Noite

Ola tudo bem

Estou efetuando um teste

E tenho o seguinte CPF valido

316.328.549-02

Mas ao informar qualquer coisa a partir do ultimo numero, também é retornado como valido

console.log(CPF.isValid("316.328.549-02"));

**Comment by fnando** [comment]
Isso é feito propositalmente.

Após validar o número do CPF/CNPJ, utilize a função `strip()` para pegar o valor final do documento.

```js
CPF.isValid('295$379\n955...93');
//=> true

CPF.strip('295$379\n955...93');
//=> 29537995593
```

**Comment by mozgbrasil** [comment]
Ola

Bom dia

Pretendo usar para validar um formulário Web

Como eu faria visando o usuário digitar algo alem de um documento valido ?

**Comment by fnando** [comment]
Acabei de adicionar uma opção para fazer validação mais estrita (e.g. `CPF.isValid(number, true)`).

**Comment by mozgbrasil** [comment]
Ola

Boa Tarde

Muito obrigado meu amigo

Sua biblioteca é fantástica, creio que a mais completa

**Comment by rogeriomq** [comment]
A validação de cpf e cnpj de forma progressiva é menos "agressiva" aos olhos de usuário final...
por exemplo:
`const cpfFormatter = (input) => {
  let str = input + ''
  str = str.replace(/\D/g, '')
  str = str.replace(/(\d{3})(\d)/, '$1.$2')
  str = str.replace(/(\d{3})(\d)/, '$1.$2')
  str = str.replace(/(\d{3})(\d{1,2})$/, '$1-$2')
  return str
}`
para CNPJ
`const cnpjFormatter = (input) => {
  let str = input + ''
  str = str.replace(/\D/g, '')
  str = str.replace(/^(\d{2})(\d)/, '$1.$2')
  str = str.replace(/^(\d{2})\.(\d{3})(\d)/, '$1.$2.$3')
  str = str.replace(/\.(\d{3})(\d)/, '.$1/$2')
  str = str.replace(/(\d{4})(\d)/, '$1-$2')
  return str
}`

Nesses formatos a cada digito informado a formatação vai acontecendo... ao contrário de somente quando todos os dígitos são informados.
